Repository Munhak-Zip/Munhak.Zip_Front, pull requests merged in 2024-05, with the labels that each got.

#27 [fix/#1] 영화 상세 이미지 변경
  src/resources/css/Movie/MovieDetail.css
  src/views/movie/MovieDetail.js
Labels: 다윤, fix, PULL REQUEST

#24 [add/#23]MovieList.js 구현
  src/App.js
  src/page/user/Main.js
  src/resources/css/Movie/MovieList.css
  src/views/movie/MovieList.js
Labels: 예진, add, PULL REQUEST

#31 [Add/#28] 헤더 추가
  src/App.js
  src/components/common/Sidebar.js
  src/components/common/header.js
  src/resources/css/Common/Sidebar.css
  src/resources/css/Common/header.css
  src/resources/img/close.png
  src/resources/img/menu.png
  src/views/movie/MovieDetail.js
Labels: 다윤, add, PULL REQUEST

#36 [fix] pr 실수한거 수정
  src/App.js
  src/page/user/Main.js
  src/resources/css/User/Login.css
  src/views/Main.js
  src/views/user/FindID.js
  src/views/user/FindPW1.js
  src/views/user/FindPW2.js
  src/views/user/FirstCheckInterest.js
  src/views/user/Login.js
  src/views/user/SignUp.js
Labels: 미현, fix, PULL REQUEST

#38 [fix/#37]Main화면 처음에 뜨도록 수정
  package-lock.json
  package.json
  src/App.js
  src/setProxy.js
Labels: 예진, fix, PULL REQUEST

#39 [add/#37]추천 영화 출력
  src/App.js
  src/views/Main.js
Labels: add, fix
