Repository Munhak-Zip/Munhak.Zip_Front, pull requests merged in 2024-06, with the labels that each got.

#40 [feat/#37]영화 출력 화면
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
  src/setProxy.js
  src/views/Main.js
Labels: 다윤, 예진, add, PULL REQUEST

#42 [add/#41]회원가입 백엔드 연동 완료
  .idea/dbnavigator.xml
  src/components/common/Sidebar.js
  src/components/common/header.js
  src/views/user/Login.js
  src/views/user/SignUp.js
Labels: 민영

#44 [add/#12]프론트 로그인 백엔드 연동 완료 (스프링시큐리티)
  package.json
  public/favicon.ico
  src/App.js
  src/views/user/Login.js
Labels: 민영, add, PULL REQUEST

#46 [fix#45] MovieDetail.js로 이동
  src/App.js
  src/views/Main.js
  src/views/movie/MovieDetail.js
Labels: 다윤, 예진, fix, PULL REQUEST

#47 [feat/#45] 영화 디테일 연결
  src/page/user/Main.js
  src/resources/css/Movie/MovieDetail.css
  src/views/Main.js
  src/views/movie/MovieDetail.js
Labels: 다윤, 예진, PULL REQUEST, feat

#48 [add#45]Reserve.js 연결
  src/App.js
  src/views/movie/MovieDetail.js
  src/views/movie/Reserve.js
Labels: 다윤, 예진, add, PULL REQUEST, feat

#49 [fea/#45] 영화 예매 화면
  src/views/movie/Reserve.js
Labels: 다윤, 예진, PULL REQUEST, feat

#50 [feat/#45] 추천영화 로딩 화면 구현
  package-lock.json
  package.json
  src/views/Main.js
Labels: 다윤, 예진, PULL REQUEST, feat

#53 [fix/#52]로그인 여부에 따른 사이드 바 화면 조절
  src/App.js
  src/axiosConfig.js
  src/components/common/Sidebar.js
  src/components/common/header.js
  src/views/mypage/Mypage.js
  src/views/user/Login.js
  src/views/user/Logout.js
Labels: 민영, fix, PULL REQUEST

#54 [feat#45]예매 -> 마이페이지
  src/App.js
  src/views/mypage/Mypage.js
Labels: 다윤, 예진, PULL REQUEST, feat

#56 [add/#55] 사용자 고유 아이디 가져오기
  src/components/common/header.js
  src/index.js
  src/views/Main.js
  src/views/mypage/Mypage.js
Labels: 민영, add, PULL REQUEST

#57 [feat/#45] 예매내역 마이페이지 출력
  src/resources/css/Mypage/Mypage.css
  src/views/movie/Reserve.js
  src/views/mypage/Mypage.js
Labels: 다윤, 예진, PULL REQUEST, feat

#59 [feat/#58]최신 영화 5개 조회
  src/views/Main.js
Labels: 예진, PULL REQUEST, feat

#60 [feat/#45]아이디 세션 변경
  src/App.js
  src/views/movie/Reserve.js
  src/views/mypage/Mypage.js
Labels: 다윤, fix, PULL REQUEST

#62 [feat/#61]리뷰 작성 추가
  src/views/movie/MovieDetail.js
Labels: 예진, PULL REQUEST, feat

#65 [feat/#64] 평론가 리뷰 제공
  src/views/movie/MovieDetail.js
Labels: 다윤, PULL REQUEST, feat

#67 [add/#63]로그인한 후 취향 고르기 추가/ [add/#66] 나의 리뷰 보관함 프론트 화면 추가
  src/App.js
  src/components/Modal/Modal.js
  src/components/interest/Interest.js
  src/resources/css/Interest/interest.css
  src/resources/css/Modal/Modal.css
  src/resources/css/Mypage/Mypage.css
  src/resources/css/Wish/ReviewBox.css
  src/views/Main.js
  src/views/mypage/Mypage.js
  src/views/user/Login.js
  src/views/user/SignUp.js
  src/views/wish/MyReviewBoxUpdate.js
  src/views/wish/ReviewBoxDetail.js
Labels: 민영, add, PULL REQUEST

#69 [feat/#68] 영화 검색
  src/App.js
  src/resources/css/Movie/MovieList.css
  src/views/Main.js
  src/views/movie/MovieDetail.js
  src/views/movie/SearchMovie.js
Labels: 다윤, PULL REQUEST, feat

#70 [feat/#61]내가 쓴 리뷰 조회
  src/App.js
  src/views/wish/MyReviewDetail.js
  src/views/wish/MyReviewList.js
Labels: 예진, PULL REQUEST, feat

#74 [fix/#72] wish.js & wish.css (아마도)최종 수정본
  src/resources/css/Wish/Wish.css
  src/views/wish/Wish.js
Labels: 미현, fix, PULL REQUEST

#75 [feat/#71] 영화 찜 추가, 삭제
  src/resources/img/Movie/bookmark.png
  src/resources/img/Movie/bookmarkC.png
  src/views/movie/MovieDetail.js
Labels: 다윤, PULL REQUEST, feat

#77 [feat/#76] 메인화면 보관함 영화 출력
  src/resources/css/Main/Main.css
  src/views/Main.js
  src/views/movie/MovieDetail.js
Labels: 다윤, PULL REQUEST, feat

#79 [feat/#61]리뷰 crud 완료
  src/App.js
  src/resources/css/Wish/ReviewBox.css
  src/views/wish/MyReviewBoxUpdate.js
  src/views/wish/MyReviewList.js
  src/views/wish/ReviewBoxDetail.js
Labels: 예진, PULL REQUEST, feat

#80 [add/#52]아이디 찾기, 비밀번호 찾기, [add/#63]로그인 이후 취향 추가 예외 처리
  src/components/interest/Interest.js
  src/views/user/FindID.js
  src/views/user/FindPW1.js
  src/views/user/FindPW2.js
  src/views/user/Login.js
Labels: 민영, add, fix, PULL REQUEST

#81 [feat] 마이페이지 회원 정보 출력 #76
  src/views/mypage/Mypage.js
Labels: 다윤, PULL REQUEST, feat

#83 [feat/#61]리뷰 작성 오류 수정
  src/views/movie/MovieDetail.js
Labels: 예진, PULL REQUEST, feat
